import { getRawgMetadataWithCoverFallback } from './gameCoverImages';
import { getCachedRawgMetadata, saveRawgMetadataCacheEntry } from './rawgMetadataCache';
import { isHighConfidenceMatch, normalizeTitle, rankRawgMatches } from './rawgMatchScoring';
import { resolveRetroTitle } from './retroTitleResolver';
import { getGameDetails, mapRawgDetailsToMetadata, RawgApiError, searchGameByName } from '../services/rawgApi';
import type { Game } from '../types/game';
import type { RawgMetadata, RawgSearchResult } from '../types/rawg';

export type SingleGameMetadataRefreshResult =
  | {
      metadata: RawgMetadata;
      status: 'updated';
      /** The search title that produced the match — save as game.metadataSearchTitle to speed future lookups */
      winningSearchTitle?: string;
    }
  | {
      status: 'no-match';
    };

/**
 * Returns an ordered list of candidate search titles for a retro ROM game, or null for non-retro games.
 * Candidates are generated by the RetroTitleResolver using the ROM filename structure.
 */
export function getRetroMetadataSearchCandidates(game: Game): string[] | null {
  if (game.externalSource !== 'retro-rom') return null;
  if (!game.romFileName && !game.romPath) return null;
  const result = resolveRetroTitle({
    romFileName: game.romFileName,
    romPath: game.romPath,
    currentTitle: game.title,
    metadataSearchTitle: game.metadataSearchTitle,
  });
  return result.candidateTitles.length > 0 ? result.candidateTitles : null;
}

/**
 * Searches RAWG trying each candidate title in order, stopping on the first that returns results.
 * Non-no-match errors (network, rate limit) propagate immediately.
 */
export async function searchRawgWithCandidates(candidates: string[]): Promise<RawgSearchResult[]> {
  for (const candidate of candidates) {
    try {
      const results = await searchRawgWithFallback(candidate);
      if (results.length > 0) return results;
    } catch (error) {
      if (error instanceof RawgApiError && error.code === 'no-match') continue;
      throw error;
    }
  }
  return [];
}

export async function refreshRawgMetadataForGame(game: Game): Promise<SingleGameMetadataRefreshResult> {
  if (typeof game.rawgId === 'number') {
    const metadata = await fetchRawgMetadataForGame(game, game.rawgId);
    return { metadata, status: 'updated' };
  }

  const retroCandidates = getRetroMetadataSearchCandidates(game);

  if (retroCandidates && retroCandidates.length > 0) {
    // Use best candidate as both cache key and scoring title
    const winningTitle = retroCandidates[0];
    const cachedMetadata = getCachedRawgMetadata(winningTitle);
    if (cachedMetadata) return { metadata: cachedMetadata.metadata, status: 'updated', winningSearchTitle: winningTitle };

    const results = await searchRawgWithCandidates(retroCandidates);
    const matches = rankRawgMatches({ ...game, title: winningTitle }, results);
    const bestMatch = matches[0];

    if (!bestMatch || !isHighConfidenceMatch(bestMatch)) return { status: 'no-match' };

    const metadata = await fetchRawgMetadataForGame(game, bestMatch.result.id);
    saveRawgMetadataCacheEntry({ cachedAt: new Date().toISOString(), gameTitle: winningTitle, metadata, rawgId: bestMatch.result.id });
    return { metadata, status: 'updated', winningSearchTitle: winningTitle };
  }

  const searchTitle = getMetadataSearchTitle(game);
  const cachedMetadata = getCachedRawgMetadata(searchTitle);
  if (cachedMetadata) return { metadata: cachedMetadata.metadata, status: 'updated' };

  const matches = rankRawgMatches({ ...game, title: searchTitle }, await searchRawgWithFallback(searchTitle));
  const bestMatch = matches[0];

  if (!bestMatch || !isHighConfidenceMatch(bestMatch)) {
    return { status: 'no-match' };
  }

  const metadata = await fetchRawgMetadataForGame(game, bestMatch.result.id);
  saveRawgMetadataCacheEntry({
    cachedAt: new Date().toISOString(),
    gameTitle: searchTitle,
    metadata,
    rawgId: bestMatch.result.id,
  });

  return { metadata, status: 'updated' };
}

export function getMetadataSearchTitle(game: Game) {
  return (game.metadataSearchTitle || game.displayTitleOverride || game.title).trim() || game.title;
}

async function fetchRawgMetadataForGame(game: Game, rawgId: number) {
  const details = await getGameDetails(rawgId);
  return getRawgMetadataWithCoverFallback(game, mapRawgDetailsToMetadata(details));
}

export async function searchRawgWithFallback(title: string) {
  const queries = getRawgSearchQueries(title);
  const resultsById = new Map<number, RawgSearchResult>();
  let lastError: unknown = null;

  for (const query of queries) {
    try {
      const results = await searchGameByName(query);
      results.forEach((result) => resultsById.set(result.id, result));
    } catch (error) {
      lastError = error;
    }
  }

  const results = Array.from(resultsById.values());

  if (results.length > 0) {
    return results;
  }

  if (lastError instanceof RawgApiError && lastError.code === 'no-match') {
    return [];
  }

  throw lastError ?? new RawgApiError('No RAWG matches found for this title.', 'no-match');
}

function getRawgSearchQueries(title: string) {
  const normalizedTitle = normalizeTitle(title);
  const titleWithoutSubtitle = title.split(/\s+[-:]\s+/)[0]?.trim() ?? title;

  return Array.from(new Set([title.trim(), normalizedTitle, titleWithoutSubtitle].filter(Boolean)));
}
