import { getRuntimeEnvironment } from '../capacitorEnvironment';
import { loadAnalyticsSettings } from './settings';
import { analyticsEventNames, analyticsSchemaVersion, telemetryEventRegistry, type AnalyticsEventName, type AnalyticsRuntime, type MinimalAnalyticsEvent, type TelemetryProperties } from './types';

const appVersion = '0.1.0';
const MAX_CLIENT_EVENTS_PER_MINUTE = 500;
const allowedEnvelopeFields = new Set(['schemaVersion','eventName','eventId','timestamp','appVersion','runtime','sessionId']);
const telemetryDebugStorageKey = 'questshelf.telemetryDebug.v1';
const sentOnceKeys = new Set<string>();
let rateWindowStartedAt = 0;
let rateWindowCount = 0;
let sessionId: string | null = null;

export type AnalyticsConfig = { enabled: boolean; endpointUrl: string };
export type TrackAnalyticsOptions = { fetcher?: typeof fetch; now?: () => Date; onceKey?: string; config?: AnalyticsConfig };
export type TelemetryDebugResult = { sent: boolean; telemetryEnabled: boolean; endpointConfigured: boolean; requestHost: string | null; status?: number; responseText?: string; error?: string; configProblem?: string };

export function getAnalyticsConfig(): AnalyticsConfig { return { enabled: import.meta.env.VITE_QS_ANALYTICS_ENABLED === 'true', endpointUrl: (import.meta.env.VITE_QS_ANALYTICS_ENDPOINT_URL ?? '/api/telemetry').trim() || '/api/telemetry' }; }
export function describeAnalyticsConfigProblem(config: AnalyticsConfig): string | null { if (config.enabled !== true) return 'VITE_QS_ANALYTICS_ENABLED is not "true" in this build'; if (!config.endpointUrl) return 'VITE_QS_ANALYTICS_ENDPOINT_URL is empty in this build'; if (config.endpointUrl.includes('example.invalid')) return 'VITE_QS_ANALYTICS_ENDPOINT_URL is still the example.invalid placeholder'; return null; }
export function isAnalyticsConfigured(config: AnalyticsConfig) { return describeAnalyticsConfigProblem(config) === null; }
export function isTelemetryDebugMode() { if (import.meta.env.DEV) return true; if (typeof window === 'undefined') return false; try { const params = new URLSearchParams(window.location.search); if (params.get('qsTelemetryDebug') === '1') { window.localStorage.setItem(telemetryDebugStorageKey, '1'); return true; } return window.localStorage.getItem(telemetryDebugStorageKey) === '1'; } catch { return false; } }
function analyticsDebug(message: string, ...details: unknown[]) { if (isTelemetryDebugMode()) console.debug('[Questory analytics]', message, ...details); }
function analyticsWarn(message: string) { if (isTelemetryDebugMode()) console.warn('[Questory analytics]', message); }
function getSafeEndpointLabel(endpointUrl: string) { if (endpointUrl.startsWith('/')) return endpointUrl; try { return new URL(endpointUrl).host; } catch { return null; } }
async function readSafeResponseText(response: Response) { const contentType = response.headers.get('content-type') ?? ''; if (!contentType || /^(text\/|application\/(json|problem\+json))/.test(contentType)) return (await response.text()).slice(0, 500); return `[response body omitted: ${contentType}]`; }

export function getAnalyticsRuntime(): AnalyticsRuntime { try { const environment = getRuntimeEnvironment(); if (environment.isAndroid) return 'capacitor_android'; if (typeof window !== 'undefined' && window.matchMedia?.('(display-mode: standalone)').matches) return 'pwa'; if (!environment.isNative) return 'browser'; } catch { return 'unknown'; } return 'unknown'; }
function getSessionId() { if (!sessionId) sessionId = crypto.randomUUID(); return sessionId; }
function isAllowedValue(eventName: AnalyticsEventName, key: string, value: unknown) { const schema = telemetryEventRegistry[eventName]; const enumValues = (schema.enums as Record<string, readonly string[]>)[key]; if (enumValues) return typeof value === 'string' && enumValues.includes(value); if (key === 'telemetry_schema_version') return value === analyticsSchemaVersion; return typeof value === 'boolean'; }
function shouldDropForRateLimit(now = Date.now()) { if (now - rateWindowStartedAt > 60000) { rateWindowStartedAt = now; rateWindowCount = 0; } rateWindowCount += 1; return rateWindowCount > MAX_CLIENT_EVENTS_PER_MINUTE; }
export function buildAnalyticsEvent(eventName: AnalyticsEventName, properties: TelemetryProperties = {}, options: Pick<TrackAnalyticsOptions, 'now'> = {}): MinimalAnalyticsEvent { return { schemaVersion: analyticsSchemaVersion, eventName, eventId: crypto.randomUUID(), timestamp: (options.now?.() ?? new Date()).toISOString(), appVersion, runtime: getAnalyticsRuntime(), sessionId: getSessionId(), ...properties }; }
export function validateAnalyticsEvent(value: unknown): value is MinimalAnalyticsEvent { if (!value || typeof value !== 'object' || Array.isArray(value)) return false; const event = value as MinimalAnalyticsEvent; if (event.schemaVersion !== analyticsSchemaVersion) return false; if (!analyticsEventNames.includes(event.eventName)) return false; const schema = telemetryEventRegistry[event.eventName]; const propertyKeys = new Set<string>([...schema.required, ...schema.optional]); for (const key of Object.keys(event)) if (!allowedEnvelopeFields.has(key) && !propertyKeys.has(key)) return false; for (const key of schema.required) if (!(key in event) || !isAllowedValue(event.eventName, key, event[key])) return false; for (const key of schema.optional) if (key in event && !isAllowedValue(event.eventName, key, event[key])) return false; return typeof event.eventId === 'string' && event.eventId.length > 0 && event.eventId.length <= 128 && typeof event.timestamp === 'string' && event.timestamp.length > 0 && event.timestamp.length <= 128 && typeof event.appVersion === 'string' && event.appVersion.length > 0 && event.appVersion.length <= 64 && typeof event.runtime === 'string' && ['pwa','browser','capacitor_android','unknown'].includes(event.runtime) && (event.sessionId === undefined || (typeof event.sessionId === 'string' && event.sessionId.length <= 128)); }

export async function sendAnalyticsEvent(event: MinimalAnalyticsEvent, config = getAnalyticsConfig(), fetcher: typeof fetch = fetch) { if (!loadAnalyticsSettings().isAnalyticsEnabled) return; const configProblem = describeAnalyticsConfigProblem(config); if (configProblem) { analyticsWarn(`Enabled by the user but no event can be sent: ${configProblem}.`); return; } if (!validateAnalyticsEvent(event)) { analyticsDebug('Event failed validation; not sent', event); return; } if (shouldDropForRateLimit()) { analyticsDebug('Event dropped by client rate limit'); return; } try { analyticsDebug(`Sending "${event.eventName}"`, { endpoint: getSafeEndpointLabel(config.endpointUrl) }); const response = await fetcher(config.endpointUrl, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(event), keepalive: true, cache: 'no-store', credentials: 'omit' }); if (!response.ok) analyticsWarn(`Endpoint returned HTTP ${response.status} for "${event.eventName}".`); } catch (error) { analyticsDebug('Send failed — failing silently', error); } }
export async function runTelemetrySelfTest(fetcher: typeof fetch = fetch, config = getAnalyticsConfig()): Promise<TelemetryDebugResult> { const settings = loadAnalyticsSettings(); const configProblem = describeAnalyticsConfigProblem(config); const result: TelemetryDebugResult = { sent: false, telemetryEnabled: settings.isAnalyticsEnabled, endpointConfigured: !configProblem, requestHost: getSafeEndpointLabel(config.endpointUrl), configProblem: configProblem ?? undefined }; if (!settings.isAnalyticsEnabled) return result; if (configProblem) return result; const event = buildAnalyticsEvent('telemetry_test_sent', { outcome: 'accepted' }); try { const response = await fetcher(config.endpointUrl, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(event), keepalive: true, cache: 'no-store', credentials: 'omit' }); result.sent = true; result.status = response.status; result.responseText = await readSafeResponseText(response); } catch (error) { result.error = error instanceof Error ? error.message : String(error); } return result; }
export function installTelemetryDebugSelfTest() { if (typeof window === 'undefined' || !isTelemetryDebugMode()) return; window.questShelfTelemetrySelfTest = () => runTelemetrySelfTest(); analyticsDebug('Telemetry self-test installed.'); }
export function trackAnalyticsEvent(eventName: AnalyticsEventName, properties: TelemetryProperties = {}, options: TrackAnalyticsOptions = {}) { if (options.onceKey) { const key = `${eventName}:${options.onceKey}`; if (sentOnceKeys.has(key)) return; sentOnceKeys.add(key); } const event = buildAnalyticsEvent(eventName, properties, options); void sendAnalyticsEvent(event, options.config ?? getAnalyticsConfig(), options.fetcher ?? fetch); }
