/**
 * The icon vocabulary.
 *
 * AS-22: `lib/questShelfAchievements.ts` and other non-UI modules named an icon by importing the type
 * from the `Icon` COMPONENT — a domain module reaching into the UI for a name. The vocabulary is a
 * contract, so it lives here; `Icon` still owns the drawings, and re-exports the type so every
 * existing import keeps working.
 */
export type IconName =
  | 'alert-triangle'
  | 'archive'
  | 'arrow-left'
  | 'badge-100'
  | 'bookmark-pen'
  | 'check'
  | 'check-circle'
  | 'circle'
  | 'compass'
  | 'chevron-left'
  | 'chevron-right'
  | 'chevron-up'
  | 'chevron-down'
  | 'chevrons-right'
  | 'database-sparkles'
  | 'external-link'
  | 'flame'
  | 'eye-off'
  | 'gamepad-2'
  | 'gem'
  | 'handheld'
  | 'heart'
  | 'image'
  | 'image-frame'
  | 'info'
  | 'joystick'
  | 'layers'
  | 'library'
  | 'list-ordered'
  | 'list-plus'
  | 'lock'
  | 'more-horizontal'
  | 'panel-top-open'
  | 'pencil'
  | 'plus'
  | 'play-circle'
  | 'plus-square'
  | 'refresh-cw'
  | 'rocket'
  | 'search'
  | 'settings'
  | 'shopping-bag'
  | 'steam'
  | 'sparkles'
  | 'sliders-horizontal'
  | 'skull-check'
  | 'sword'
  | 'trash-2'
  | 'trophy'
  | 'x';
