import { HomePanel } from '../../../components/HomePanel';
import { ShelfAvatar } from '../../../components/ShelfIdentity';
import type { AppSectionRouterProps } from '../AppSectionRouter';

type HomeRouteProps = Pick<AppSectionRouterProps, 'personalizedQuestShelfTitle' | 'computedShelfTitle' | 'resolvedFeaturedGame' | 'shelfIdentity' | 'steamAvatarUrl' | 'games' | 'reviewIgnoredGameIds' | 'playActivity' | 'reviewModeState' | 'platformQueueState' | 'itadDealSyncState' | 'steamAchievementSyncState' | 'steamPlaytimeRefreshState' | 'isImportingNewSteamGames' | 'openGameFromHome' | 'setSelectedGameId' | 'setActiveNavItem' | 'setActiveSettingsCategory' | 'openQueue' | 'startReviewMode' | 'playQueueGameNow' | 'logPlayedToday' | 'addToastNotification' | 'updateGameTracking' | 'updateGameStatusWithCompletion' | 'syncWishlistDeals' | 'importNewSteamGames' | 'setIsAchievementTimelineOpen' | 'syncSteamAchievements' | 'refreshSteamPlaytime' | 'homeSteamSyncGameIds' | 'handleSelectDiscoveryGame' | 'openDiscoveryPreview' | 'discoveryInboxRawgIds'>;

export function HomeRoute({ personalizedQuestShelfTitle, computedShelfTitle, resolvedFeaturedGame, shelfIdentity, steamAvatarUrl, games, reviewIgnoredGameIds, playActivity, reviewModeState, platformQueueState, itadDealSyncState, steamAchievementSyncState, steamPlaytimeRefreshState, isImportingNewSteamGames, openGameFromHome, setSelectedGameId, setActiveNavItem, setActiveSettingsCategory, openQueue, startReviewMode, playQueueGameNow, logPlayedToday, addToastNotification, updateGameTracking, updateGameStatusWithCompletion, syncWishlistDeals, importNewSteamGames, setIsAchievementTimelineOpen, syncSteamAchievements, refreshSteamPlaytime, homeSteamSyncGameIds, handleSelectDiscoveryGame, openDiscoveryPreview, discoveryInboxRawgIds }: HomeRouteProps) {
  return <HomePanel appTitle={personalizedQuestShelfTitle} shelfTitle={computedShelfTitle} featuredGame={resolvedFeaturedGame} avatar={<ShelfAvatar {...shelfIdentity} steamAvatarUrl={steamAvatarUrl} sizeClassName="h-14 w-14" />} games={games} ignoredReviewGameIds={reviewIgnoredGameIds} playActivity={playActivity} reviewQueueOrder={reviewModeState.queueOrder} reviewModeState={reviewModeState} queueState={platformQueueState} itadDealSyncState={itadDealSyncState} steamAchievementSyncState={steamAchievementSyncState} steamPlaytimeRefreshState={steamPlaytimeRefreshState} isImportingNewSteamGames={isImportingNewSteamGames} onOpenDetails={openGameFromHome} onOpenLibrary={() => { setSelectedGameId(null); setActiveNavItem('Library'); }} onOpenQueue={openQueue} onOpenReviewMode={startReviewMode} onOpenSettings={() => { setSelectedGameId(null); setActiveNavItem('Settings'); setActiveSettingsCategory('Personalization'); }} onOpenIntegrationsSettings={() => { setSelectedGameId(null); setActiveNavItem('Settings'); setActiveSettingsCategory('Integrations'); }} onOpenWishlist={() => { setSelectedGameId(null); setActiveNavItem('Wishlist'); }} onPlayToday={(game) => { if (game.status === 'Playing') { logPlayedToday(game); addToastNotification({ category: 'success', dedupeKey: `play-today:${game.id}`, message: `${game.title} is already in Playing Now.` }); return; } const targetPlatform = platformQueueState.entries.find((e) => e.gameId === game.id)?.targetPlatform ?? game.platform; playQueueGameNow(game.id, targetPlatform); logPlayedToday(game); }} onQuickNote={(gameId, notes) => { const target = games.find((g) => g.id === gameId); if (!target) return; updateGameTracking(gameId, { notes, status: target.status, tags: target.tags }); addToastNotification({ category: 'success', dedupeKey: `quick-note:${gameId}`, message: 'Note saved.' }); }} onStatusChange={updateGameStatusWithCompletion} onSyncItadDeals={() => { const wishlistIds = games.filter((g) => g.collectionType === 'wishlist').map((g) => g.id); void syncWishlistDeals(wishlistIds); }} onImportNewSteamGames={() => { void importNewSteamGames(); }} onOpenAchievementTimeline={() => setIsAchievementTimelineOpen(true)} onSyncSteamAchievements={() => { void syncSteamAchievements(homeSteamSyncGameIds, { emptyToastMessage: 'No Playing Now or Platform Plan Steam games are eligible for achievement sync.', showToast: true }); }} onSyncSteamPlaytime={() => { void refreshSteamPlaytime(homeSteamSyncGameIds, { emptyToastMessage: 'No Playing Now or Platform Plan Steam games are eligible for playtime sync.', showToast: true }); }} onSelectDiscoveryGame={handleSelectDiscoveryGame} onOpenDiscoveryPreview={openDiscoveryPreview} discoveryInboxRawgIds={discoveryInboxRawgIds} />;
}
