import { CollectionPanel } from '../../collection/CollectionPanel';
import { formatMessageTemplate, formatSteamAchievementSyncSummary } from '../../../utils/summaryFormatters';
import type { AppSectionRouteModel } from '../AppSectionRouter';

type LibraryRouteProps = Pick<AppSectionRouteModel, 'mainContentRef' | 'libraryFilters' | 'steamAchievementSyncState' | 'steamPlaytimeRefreshState' | 'filteredLibraryGames' | 'games' | 'reviewIgnoredGameIds' | 'reviewModeState' | 'platformOptions' | 'tags' | 'platformQueueState' | 'isHltbSyncing' | 'setIsAddGameOpen' | 'addToWishlist' | 'addManyToWishlist' | 'refreshGameMetadataFromActions' | 'moveToLibrary' | 'handleOpenDetailsFromCollection' | 'removeGame' | 'removeAndIgnoreSteamGame' | 'updateGameStatusWithCompletion' | 'startMetadataWorkflow' | 'removeManyGames' | 'removeAndIgnoreManyGames' | 'updateManyGameStatuses' | 'syncHltb' | 'syncSteamAchievements' | 'refreshSteamPlaytime' | 'openBacklogPicker' | 'startReviewMode' | 'playGameFromCompactRow' | 'finishGameFromCompactRow' | 'dropGameFromCompactRow' | 'importMultiGameItemsWithAnalytics' | 'handleClearLibraryFilters' | 'handleLibraryFiltersChange' | 'openOnboarding' | 'setActiveNavItem' | 'setActiveSettingsCategory' | 't'>;

export function LibraryRoute(props: LibraryRouteProps) {
  const { mainContentRef, libraryFilters, steamAchievementSyncState, steamPlaytimeRefreshState, filteredLibraryGames, games, reviewIgnoredGameIds, reviewModeState, platformOptions, tags, platformQueueState, isHltbSyncing, setIsAddGameOpen, addToWishlist, addManyToWishlist, refreshGameMetadataFromActions, moveToLibrary, handleOpenDetailsFromCollection, removeGame, removeAndIgnoreSteamGame, updateGameStatusWithCompletion, startMetadataWorkflow, removeManyGames, removeAndIgnoreManyGames, updateManyGameStatuses, syncHltb, syncSteamAchievements, refreshSteamPlaytime, openBacklogPicker, startReviewMode, playGameFromCompactRow, finishGameFromCompactRow, dropGameFromCompactRow, importMultiGameItemsWithAnalytics, handleClearLibraryFilters, handleLibraryFiltersChange, openOnboarding, setActiveNavItem, setActiveSettingsCategory, t } = props;
  return <CollectionPanel collectionType="library" contentScrollRef={mainContentRef} filters={libraryFilters} steamAchievementSyncState={steamAchievementSyncState} steamPlaytimeRefreshState={steamPlaytimeRefreshState} games={filteredLibraryGames} allGames={games} ignoredReviewGameIds={reviewIgnoredGameIds} reviewModeState={reviewModeState} platformOptions={platformOptions} tags={tags} platformQueueState={platformQueueState} isHltbSyncing={isHltbSyncing} collectionActions={{ addGame: () => setIsAddGameOpen(true), addToWishlist, addManyToWishlist, findArtwork: (game) => refreshGameMetadataFromActions(game, 'artwork'), findMetadata: refreshGameMetadataFromActions, moveToLibrary, openDetails: handleOpenDetailsFromCollection, remove: removeGame, removeAndIgnore: removeAndIgnoreSteamGame, statusChange: updateGameStatusWithCompletion }} bulkActions={{ enrich: startMetadataWorkflow, remove: removeManyGames, removeAndIgnore: removeAndIgnoreManyGames, statusChange: updateManyGameStatuses, syncHltb, syncSteamAchievements: (gameIds, options) => syncSteamAchievements(gameIds, { completionToastMessage: formatSteamAchievementSyncSummary, emptyToastMessage: options?.emptyToastMessage, force: options?.force, showToast: true }), refreshSteamPlaytime: (gameIds, options) => refreshSteamPlaytime(gameIds, { completionToastMessage: (summary) => formatMessageTemplate(t('app.updatedPlaytimeForGames'), { count: summary.updatedCount }), emptyToastMessage: options?.emptyToastMessage, showToast: true }) }} queueActions={{ addToQueue: openBacklogPicker, openQueue: () => startReviewMode('backlog'), playNow: playGameFromCompactRow, finish: finishGameFromCompactRow, drop: dropGameFromCompactRow }} reviewActions={{ startReview: startReviewMode }} syncActions={{ importMultiGames: importMultiGameItemsWithAnalytics }} filterActions={{ clearFilters: handleClearLibraryFilters, filtersChange: handleLibraryFiltersChange }} navigationActions={{ openOnboarding, openIntegrations: () => { setActiveNavItem('Settings'); setActiveSettingsCategory('Integrations'); }, openRetro: () => { setActiveNavItem('Settings'); setActiveSettingsCategory('Retro'); } }} />;
}
