import { CollectionPanel } from '../../collection/CollectionPanel';
import type { AppSectionRouterProps } from '../AppSectionRouter';

type WishlistRouteProps = Pick<AppSectionRouterProps, 'mainContentRef' | 'wishlistFilters' | 'filteredWishlistGames' | 'platformOptions' | 'steamWishlistSyncState' | 'itadDealSyncState' | 'tags' | 'platformQueueState' | 'isHltbSyncing' | 'setIsAddGameOpen' | 'addToWishlist' | 'addManyToWishlist' | 'refreshGameMetadataFromActions' | 'moveToLibrary' | 'handleOpenDetailsFromCollection' | 'removeGame' | 'removeAndIgnoreSteamGame' | 'updateGameStatusWithCompletion' | 'startMetadataWorkflow' | 'removeManyGames' | 'removeAndIgnoreManyGames' | 'updateManyGameStatuses' | 'syncHltb' | 'openBacklogPicker' | 'playGameFromCompactRow' | 'finishGameFromCompactRow' | 'dropGameFromCompactRow' | 'startReviewMode' | 'handleClearWishlistFilters' | 'handleWishlistFiltersChange' | 'syncSteamWishlist' | 'importSteamWishlistHtmlItemsWithAnalytics' | 'syncWishlistDeals'>;

export function WishlistRoute(props: WishlistRouteProps) {
  const { mainContentRef, wishlistFilters, filteredWishlistGames, platformOptions, steamWishlistSyncState, itadDealSyncState, tags, platformQueueState, isHltbSyncing, setIsAddGameOpen, addToWishlist, addManyToWishlist, refreshGameMetadataFromActions, moveToLibrary, handleOpenDetailsFromCollection, removeGame, removeAndIgnoreSteamGame, updateGameStatusWithCompletion, startMetadataWorkflow, removeManyGames, removeAndIgnoreManyGames, updateManyGameStatuses, syncHltb, openBacklogPicker, playGameFromCompactRow, finishGameFromCompactRow, dropGameFromCompactRow, startReviewMode, handleClearWishlistFilters, handleWishlistFiltersChange, syncSteamWishlist, importSteamWishlistHtmlItemsWithAnalytics, syncWishlistDeals } = props;
  return <CollectionPanel collectionType="wishlist" contentScrollRef={mainContentRef} filters={wishlistFilters} games={filteredWishlistGames} platformOptions={platformOptions} steamWishlistSyncState={steamWishlistSyncState} itadDealSyncState={itadDealSyncState} tags={tags} platformQueueState={platformQueueState} isHltbSyncing={isHltbSyncing} collectionActions={{ addGame: () => setIsAddGameOpen(true), addToWishlist, addManyToWishlist, findArtwork: (game) => refreshGameMetadataFromActions(game, 'artwork'), findMetadata: refreshGameMetadataFromActions, moveToLibrary, openDetails: handleOpenDetailsFromCollection, remove: removeGame, removeAndIgnore: removeAndIgnoreSteamGame, statusChange: updateGameStatusWithCompletion }} bulkActions={{ enrich: startMetadataWorkflow, remove: removeManyGames, removeAndIgnore: removeAndIgnoreManyGames, statusChange: updateManyGameStatuses, syncHltb }} queueActions={{ addToQueue: openBacklogPicker, playNow: playGameFromCompactRow, finish: finishGameFromCompactRow, drop: dropGameFromCompactRow }} reviewActions={{ startReview: startReviewMode }} filterActions={{ clearFilters: handleClearWishlistFilters, filtersChange: handleWishlistFiltersChange }} syncActions={{ syncSteamWishlist, importSteamWishlistHtml: importSteamWishlistHtmlItemsWithAnalytics, syncItadDeals: syncWishlistDeals }} />;
}
