import { analyticsSchemaVersion, telemetryEnvelopeFields, telemetryEventRegistry, telemetryRuntimes, telemetrySensitiveFields } from './telemetry-schema.js';
const telemetryProvider = 'telemetry';
const MAX_BODY_BYTES = 8192;
const UPSTREAM_TIMEOUT_MS = 5000;
// AS-17: the envelope, the privacy denylist and the runtimes come from the generated contract too —
// there is no hand-kept copy of any of them left in this file.
const allowedEnvelopeFields = new Set(telemetryEnvelopeFields);
const sensitiveFields = new Set(telemetrySensitiveFields);
function sendJson(res, status, body) { res.setHeader('Content-Type', 'application/json; charset=utf-8'); res.setHeader('Cache-Control', 'no-store'); res.status(status).json(body); }
function fail(status, code, error) { const err = new Error(error); err.status = status; err.code = code; return err; }
function normalizeWebhookUrl(value) { return String(value || '').trim().replace(/^[ '"`]+|[ '"`]+$/g, ''); }
function getBodySize(req) { const header = req.headers?.['content-length']; const parsed = Number(Array.isArray(header) ? header[0] : header); if (Number.isFinite(parsed)) return parsed; try { return Buffer.byteLength(JSON.stringify(req.body || {}), 'utf8'); } catch { return 0; } }
function isAllowedValue(schema, key, value) { const enumValues = schema.enums?.[key]; if (enumValues) return typeof value === 'string' && enumValues.includes(value); if (key === 'telemetry_schema_version') return value === analyticsSchemaVersion; return typeof value === 'boolean'; }
export function validateEvent(body) { if (!body || typeof body !== 'object' || Array.isArray(body)) throw fail(400, 'INVALID_BODY', 'Telemetry request body must be a JSON object.'); if (body.schemaVersion !== analyticsSchemaVersion) throw fail(400, 'INVALID_SCHEMA_VERSION', 'Unsupported telemetry schema version.'); const eventName = body.eventName; const schema = telemetryEventRegistry[eventName]; if (typeof eventName !== 'string' || !schema) throw fail(400, 'INVALID_EVENT_NAME', 'Unsupported telemetry event name.'); const propertyKeys = new Set([...(schema.required || []), ...(schema.optional || [])]); for (const key of Object.keys(body)) { if (sensitiveFields.has(key)) throw fail(400, 'PRIVACY_FIELD_REJECTED', 'Telemetry payload contains privacy-sensitive fields.'); if (!allowedEnvelopeFields.has(key) && !propertyKeys.has(key)) throw fail(400, 'UNSUPPORTED_FIELD', 'Telemetry payload contains unsupported fields.'); }
  for (const key of schema.required || []) if (!(key in body) || !isAllowedValue(schema, key, body[key])) throw fail(400, `INVALID_${key.toUpperCase()}`, 'Telemetry payload contains invalid event properties.');
  for (const key of schema.optional || []) if (key in body && !isAllowedValue(schema, key, body[key])) throw fail(400, `INVALID_${key.toUpperCase()}`, 'Telemetry payload contains invalid event properties.');
  for (const key of ['eventId','timestamp','appVersion']) if (typeof body[key] !== 'string' || body[key].length < 1 || body[key].length > 128) throw fail(400, `INVALID_${key.toUpperCase()}`, 'Telemetry payload contains invalid string fields.');
  if (!telemetryRuntimes.includes(body.runtime)) throw fail(400, 'INVALID_RUNTIME', 'Unsupported telemetry runtime.');
  if (body.sessionId !== undefined && (typeof body.sessionId !== 'string' || body.sessionId.length > 128)) throw fail(400, 'INVALID_SESSION_ID', 'Telemetry payload contains invalid string fields.');
  return body; }
async function forwardToMake(event, webhookUrl) { const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), UPSTREAM_TIMEOUT_MS); try { const response = await fetch(webhookUrl, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(event), signal: controller.signal }); if (!response.ok) return { accepted: false, upstreamStatus: response.status }; return { accepted: true, upstreamStatus: response.status }; } finally { clearTimeout(timeout); } }
export default async function handler(req, res) { if (req.method !== 'POST') { res.setHeader('Allow', 'POST'); return sendJson(res, 405, { success: false, provider: telemetryProvider, code: 'METHOD_NOT_ALLOWED', error: 'Use POST for telemetry requests.' }); } try { if (getBodySize(req) > MAX_BODY_BYTES) throw fail(413, 'PAYLOAD_TOO_LARGE', 'Telemetry payload is too large.'); const event = validateEvent(req.body); const webhookUrl = normalizeWebhookUrl(process.env.QS_ANALYTICS_WEBHOOK_URL || process.env.MAKE_TELEMETRY_WEBHOOK_URL); if (!webhookUrl || webhookUrl.includes('example.invalid')) throw fail(503, 'TELEMETRY_NOT_CONFIGURED', 'Telemetry forwarding is not configured.'); const parsedUrl = new URL(webhookUrl); if (!['https:', 'http:'].includes(parsedUrl.protocol)) throw fail(503, 'TELEMETRY_NOT_CONFIGURED', 'Telemetry forwarding is not configured.'); const result = await forwardToMake(event, parsedUrl.toString()); if (!result.accepted) return sendJson(res, 502, { success: false, provider: telemetryProvider, code: 'UPSTREAM_REJECTED', status: result.upstreamStatus, error: 'Telemetry endpoint rejected the event.' }); return sendJson(res, 202, { success: true, provider: telemetryProvider, accepted: true, status: result.upstreamStatus }); } catch (error) { if (error?.name === 'AbortError') return sendJson(res, 504, { success: false, provider: telemetryProvider, code: 'UPSTREAM_TIMEOUT', error: 'Telemetry endpoint timed out.' }); const status = error?.status || 500; if (process.env.NODE_ENV !== 'production' && status >= 500) console.warn('[telemetry]', { code: error?.code || 'TELEMETRY_ERROR', status }); return sendJson(res, status, { success: false, provider: telemetryProvider, code: error?.code || 'TELEMETRY_ERROR', error: status >= 500 ? 'Telemetry forwarding failed.' : error.message }); } }
