// GENERATED FILE — do not edit by hand.
//
// Source of truth: src/lib/analytics/telemetryContract.ts
// Regenerate:      npm run generate:telemetry-schema
//
// AS-17: the client registry and this allowlist used to be maintained separately and had drifted —
// live recommendation and Discovery events were rejected in production as INVALID_EVENT_NAME while
// every test passed. There is one contract now, and this file is its server projection.

export const analyticsSchemaVersion = 2;
export const telemetryEnvelopeFields = ["schemaVersion","eventName","eventId","timestamp","appVersion","runtime","sessionId"];
export const telemetrySensitiveFields = ["gameTitle","title","gameId","rawgId","steamId","steamAccountId","email","userName","platformName","collectionName","text","notes","artworkUrl","screenshotUrl","apiKey","webhookUrl","backup","library","achievementName","stack","message","errorMessage"];
export const telemetryRuntimes = ["pwa","browser","capacitor_android","unknown"];

export const telemetryEventRegistry = {
  app_session_started: { status: "active", required: ["install_mode","library_size_bucket","has_completed_onboarding","telemetry_schema_version"], optional: [], enums: { runtime: ["pwa","browser","capacitor_android","unknown"], install_mode: ["installed","browser_tab","unknown"], library_size_bucket: ["empty","1_25","26_100","101_300","301_1000","1000_plus"] } },
  onboarding_completed: { status: "active", required: ["completion_path","integrations_configured_bucket"], optional: [], enums: { completion_path: ["fresh_install","existing_library","skipped_optional_steps"], integrations_configured_bucket: ["none","one","multiple"] } },
  onboarding_reset: { status: "reserved", required: [], optional: [], enums: {} },
  telemetry_enabled: { status: "active", required: ["source"], optional: [], enums: { source: ["onboarding","settings"] } },
  telemetry_disabled: { status: "active", required: ["source"], optional: [], enums: { source: ["settings"] } },
  telemetry_test_sent: { status: "active", required: ["outcome"], optional: [], enums: { outcome: ["accepted","configuration_missing","rejected","network_error","timeout"] } },
  library_import_started: { status: "reserved", required: ["source"], optional: [], enums: { source: ["steam","playstation_bookmarklet","nintendo_bookmarklet","retro_file","manual","backup_restore","other"] } },
  library_import_completed: { status: "active", required: ["source","outcome","imported_count_bucket","duplicate_count_bucket","duration_bucket"], optional: ["error_category"], enums: { source: ["steam","playstation_bookmarklet","nintendo_bookmarklet","retro_file","manual","backup_restore","other"], outcome: ["success","partial_success","cancelled","failed"], imported_count_bucket: ["zero","1_10","11_50","51_200","201_500","500_plus"], duplicate_count_bucket: ["zero","1_10","11_50","51_plus"], duration_bucket: ["under_2s","2_10s","10_30s","30_120s","over_120s"], error_category: ["network","authentication","invalid_input","provider_unavailable","parsing","storage","unknown"] } },
  integration_connected: { status: "reserved", required: ["integration","outcome"], optional: ["error_category"], enums: { integration: ["steam","rawg","steamgriddb","itad","hltb","other"], outcome: ["success","failed"], error_category: ["network","authentication","invalid_input","provider_unavailable","parsing","storage","unknown"] } },
  sync_started: { status: "reserved", required: ["sync_type","scope_bucket"], optional: [], enums: { sync_type: ["steam_library","steam_playtime","steam_achievements","metadata","wishlist_deals","artwork","full_maintenance","other"], scope_bucket: ["one","2_10","11_50","51_200","200_plus"] } },
  sync_completed: { status: "reserved", required: ["sync_type","outcome","changed_count_bucket","failed_count_bucket","duration_bucket"], optional: ["error_category"], enums: { sync_type: ["steam_library","steam_playtime","steam_achievements","metadata","wishlist_deals","artwork","full_maintenance","other"], outcome: ["success","partial_success","failed","cancelled"], changed_count_bucket: ["zero","1_10","11_50","51_200","201_500","500_plus"], failed_count_bucket: ["zero","1_10","11_50","51_plus"], duration_bucket: ["under_2s","2_10s","10_30s","30_120s","over_120s"], error_category: ["network","authentication","invalid_input","provider_unavailable","parsing","storage","unknown"] } },
  game_added: { status: "reserved", required: ["destination","source"], optional: [], enums: { destination: ["library","wishlist","platform_plan"], source: ["manual","import","discover","recommendation","quest_queue","game_detail","other"] } },
  game_status_changed: { status: "reserved", required: ["from_status","to_status","source"], optional: [], enums: { from_status: ["backlog","planned","playing","finished","dropped","ignored","wishlist","unknown"], to_status: ["backlog","planned","playing","finished","dropped","ignored","wishlist"], source: ["library","game_detail","quest_queue","platform_plans","home","other"] } },
  game_rating_saved: { status: "reserved", required: ["rating_bucket","source"], optional: [], enums: { rating_bucket: ["1","2","3","4","5"], source: ["quest_queue","game_detail","other"] } },
  bulk_action_completed: { status: "reserved", required: ["action","selected_count_bucket","outcome"], optional: [], enums: { action: ["move_platform","change_status","refresh_metadata","refresh_artwork","remove","other"], selected_count_bucket: ["zero","1_10","11_50","51_200","201_500","500_plus"], outcome: ["success","partial_success","cancelled","failed"] } },
  quest_queue_started: { status: "active", required: ["queue_source","batch_size_bucket","filter_mode"], optional: [], enums: { queue_source: ["library","wishlist","discovery","platform_plan","mixed"], batch_size_bucket: ["1_5","6_10","11_20","20_plus"], filter_mode: ["default","filtered","unknown"] } },
  quest_queue_action: { status: "reserved", required: ["action","position_bucket","source"], optional: [], enums: { action: ["add_to_plans","playing_now","wishlist","finished","dropped","ignored","skipped"], position_bucket: ["early","middle","late"], source: ["library_queue","discovery_inbox"] } },
  quest_queue_batch_completed: { status: "reserved", required: ["queue_source","initial_count_bucket","processed_count_bucket","skipped_count_bucket","completion_state","duration_bucket"], optional: [], enums: { queue_source: ["library","wishlist","discovery","platform_plan","mixed"], initial_count_bucket: ["zero","1_10","11_50","51_200","201_500","500_plus"], processed_count_bucket: ["zero","1_10","11_50","51_200","201_500","500_plus"], skipped_count_bucket: ["zero","1_10","11_50","51_plus"], completion_state: ["completed","exited_early","empty"], duration_bucket: ["under_2s","2_10s","10_30s","30_120s","over_120s"] } },
  quest_queue_screenshot_opened: { status: "reserved", required: ["source"], optional: [], enums: { source: ["library_queue","discovery_inbox"] } },
  platform_plan_created: { status: "reserved", required: ["creation_method","used_default_artwork"], optional: [], enums: { creation_method: ["manual","onboarding","imported"] } },
  platform_plan_updated: { status: "reserved", required: ["change_type"], optional: [], enums: { change_type: ["identity","artwork","ordering","games","other"] } },
  platform_plan_opened: { status: "reserved", required: ["game_count_bucket","has_currently_playing","used_default_artwork"], optional: [], enums: { game_count_bucket: ["empty","1_5","6_20","21_50","50_plus"] } },
  platform_plan_game_reordered: { status: "reserved", required: ["method"], optional: [], enums: { method: ["drag_drop","controls","other"] } },
  discover_section_opened: { status: "active", required: ["section"], optional: [], enums: { section: ["recommendations","release_calendar","discovery_inbox","similar_games","other"] } },
  discovery_recommendations_requested: { status: "active", required: ["source","requested_count_bucket","returned_count_bucket"], optional: [], enums: { source: ["discovery_inbox"], requested_count_bucket: ["zero","1_5","6_10","11_plus"], returned_count_bucket: ["zero","1_5","6_10","11_plus"] } },
  recommendation_impression: { status: "reserved", required: ["surface","recommendation_type","result_count_bucket"], optional: [], enums: { surface: ["home","game_detail","discover","release_calendar"], recommendation_type: ["personal","similar","because_you_like","release","fallback"], result_count_bucket: ["zero","1_5","6_10","11_plus"] } },
  recommendation_action: { status: "reserved", required: ["surface","recommendation_type","action","position_bucket"], optional: [], enums: { surface: ["home","game_detail","discover","release_calendar"], recommendation_type: ["personal","similar","because_you_like","release","fallback"], action: ["opened","added_to_wishlist","added_to_library","added_to_plans","dismissed"], position_bucket: ["top","middle","lower"] } },
  recommendation_generation_completed: { status: "active", required: ["outcome","result_count_bucket","duration_bucket","cache_status","partial_failure_bucket","fallback_tier"], optional: [], enums: { outcome: ["success","partial","empty","failed"], result_count_bucket: ["zero","1_5","6_10","11_plus"], duration_bucket: ["under_2s","2_10s","10_30s","30_120s","over_120s"], cache_status: ["hit","miss","stale","invalid","bypass"], partial_failure_bucket: ["zero","1_5","6_10","11_plus"], fallback_tier: ["none","personalized","adjacent","broad"] } },
  recommendation_feedback: { status: "active", required: ["surface","feedback_type","source_category","fallback_tier","rank_bucket","engine_version","scoring_version"], optional: [], enums: { surface: ["home","game_detail","discover","release_calendar"], feedback_type: ["hide","not_interested","less_like_this","already_played","more_like_this"], source_category: ["seed","affinity","intent","fallback","unknown"], fallback_tier: ["none","personalized","adjacent","broad"], rank_bucket: ["top","middle","lower"], engine_version: ["5.0.0"], scoring_version: ["5.0.0"] } },
  release_calendar_generated: { status: "reserved", required: ["result_count_bucket","personalization_mode","outcome"], optional: [], enums: { result_count_bucket: ["zero","1_5","6_10","11_plus"], personalization_mode: ["strict","relaxed","fallback"], outcome: ["success","empty","failed"] } },
  game_detail_opened: { status: "reserved", required: ["source","has_screenshots","has_achievements","has_recommendations","metadata_completeness"], optional: [], enums: { source: ["library","wishlist","home","discover","recommendation","quest_queue","platform_plans","other"], metadata_completeness: ["low","medium","high"] } },
  game_detail_section_used: { status: "reserved", required: ["section","action"], optional: [], enums: { section: ["screenshots","achievements","recommendations","metadata","actions"], action: ["opened","refreshed","expanded"] } },
  artwork_changed: { status: "reserved", required: ["source","surface"], optional: [], enums: { source: ["steamgriddb","uploaded","default","other"], surface: ["game_detail","library_action","platform_plan"] } },
  home_widget_used: { status: "reserved", required: ["widget","action"], optional: [], enums: { widget: ["next_from_plans","play_today","recommended_for_you","sync_maintenance","questory_journey","onboarding","release_calendar","other"], action: ["opened","primary_action","refreshed","dismissed"] } },
  play_today_generated: { status: "reserved", required: ["outcome","candidate_count_bucket"], optional: [], enums: { outcome: ["recommendation_available","empty","failed"], candidate_count_bucket: ["zero","1_10","11_50","51_200","201_500","500_plus"] } },
  achievements_sync_completed: { status: "reserved", required: ["outcome","game_count_bucket","unlocked_count_bucket","duration_bucket"], optional: ["error_category"], enums: { outcome: ["success","partial_success","unsupported","failed"], game_count_bucket: ["zero","1_10","11_50","51_200","201_500","500_plus"], unlocked_count_bucket: ["zero","1_10","11_50","51_200","201_500","500_plus"], duration_bucket: ["under_2s","2_10s","10_30s","30_120s","over_120s"], error_category: ["network","authentication","invalid_input","provider_unavailable","parsing","storage","unknown"] } },
  achievements_timeline_opened: { status: "reserved", required: ["source","entry_count_bucket"], optional: [], enums: { source: ["home","game_detail","other"], entry_count_bucket: ["zero","1_10","11_50","51_200","201_500","500_plus"] } },
  backup_export_completed: { status: "active", required: ["outcome","library_size_bucket","duration_bucket"], optional: ["error_category"], enums: { outcome: ["success","failed"], library_size_bucket: ["empty","1_25","26_100","101_300","301_1000","1000_plus"], duration_bucket: ["under_2s","2_10s","10_30s","30_120s","over_120s"], error_category: ["network","authentication","invalid_input","provider_unavailable","parsing","storage","unknown"] } },
  backup_restore_completed: { status: "active", required: ["outcome","restored_count_bucket","duration_bucket","migration_required"], optional: ["error_category"], enums: { outcome: ["success","partial_success","failed","cancelled"], restored_count_bucket: ["zero","1_10","11_50","51_200","201_500","500_plus"], duration_bucket: ["under_2s","2_10s","10_30s","30_120s","over_120s"], error_category: ["network","authentication","invalid_input","provider_unavailable","parsing","storage","unknown"] } },
  appearance_changed: { status: "reserved", required: ["theme","surface"], optional: [], enums: { theme: ["light","dark","system"], surface: ["settings","onboarding"] } },
  library_view_changed: { status: "reserved", required: ["view"], optional: [], enums: { view: ["grid","shelf","compact"] } },
  language_changed: { status: "reserved", required: ["language"], optional: [], enums: { language: ["cs","en","other"] } },
  operation_failed: { status: "reserved", required: ["operation","error_category","recoverable"], optional: [], enums: { operation: ["app_startup","storage_read","storage_write","library_import","metadata_fetch","artwork_fetch","recommendation_fetch","achievements_sync","backup_export","backup_restore","telemetry_proxy","other"], error_category: ["network","timeout","authentication","rate_limit","provider_unavailable","invalid_response","parsing","storage","unsupported","unknown"], runtime: ["pwa","browser","capacitor_android","unknown"] } },
};
